# ***Cloud Cost Optimizer***

## ***Data preparation***

### Using dataset.csv

In [188]:
import pandas as pd
df = pd.read_csv('dataset.csv')
df

,Name,API Name,Memory,Compute Units (ECU),vCPUs,GiB of Memory per vCPU,GPUs,GPU model,GPU memory,CUDA Compute Capability,...,Windows SQL Ent On Demand cost,Windows SQL Ent Reserved cost,Linux SQL Web On Demand cost,Linux SQL Web Reserved cost,Linux SQL Std On Demand cost,Linux SQL Std Reserved cost,Linux SQL Ent On Demand cost,Linux SQL Ent Reserved cost,EBS Optimized surcharge,EMR cost
0,M6A 24xlarge,m6a.24xlarge,384.0,0 units,96,4.00 GiB/vCPU,0,NaN,0 GiB,0.0,...,$44.5632 hourly,$43.15937 hourly,$5.7696 hourly,$4.36577 hourly,$15.6672 hourly,$14.26337 hourly,$40.1472 hourly,$38.74337 hourly,0,unavailable
1,M5DN Extra Large,m5dn.xlarge,16.0,0 units,4,4.00 GiB/vCPU,0,NaN,0 GiB,0.0,...,$1.956 hourly,$1.855 hourly,$0.34 hourly,$0.239 hourly,$0.752 hourly,$0.651 hourly,$1.772 hourly,$1.671 hourly,0,unavailable
2,C6A Eight Extra Large,c6a.8xlarge,64.0,0 units,32,2.00 GiB/vCPU,0,NaN,0 GiB,0.0,...,$14.696 hourly,$14.28168 hourly,$1.7648 hourly,$1.35048 hourly,$5.064 hourly,$4.64968 hourly,$13.224 hourly,$12.80968 hourly,0,unavailable
3,G5 Graphics and Machine Learning GPU 16xlarge,g5.16xlarge,256.0,0 units,64,4.00 GiB/vCPU,1,NVIDIA A10G,24 GiB,7.5,...,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,0,unavailable
4,R5AD 16xlarge,r5ad.16xlarge,512.0,0 units,64,8.00 GiB/vCPU,0,NaN,0 GiB,0.0,...,$31.136 hourly,$29.585 hourly,$5.274 hourly,$3.723 hourly,$11.872 hourly,$10.321 hourly,$28.192 hourly,$26.641 hourly,0,unavailable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,T3 Large,t3.large,8.0,Base performance: 60%,2,4.00 GiB/vCPU,0,NaN,0 GiB,0.0,...,unavailable,unavailable,$0.1508 hourly,$0.1198 hourly,unavailable,unavailable,unavailable,unavailable,0,unavailable
501,VT1 6xlarge,vt1.6xlarge,48.0,0 units,24,2.00 GiB/vCPU,0,NaN,0 GiB,0.0,...,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,0,unavailable
502,U-9TB1 Metal,u-9tb1.metal,9216.0,0 units,448,20.57 GiB/vCPU,0,NaN,0 GiB,0.0,...,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,0,unavailable
503,G4DN 12xlarge,g4dn.12xlarge,192.0,0 units,48,4.00 GiB/vCPU,4,NVIDIA T4 Tensor Core,64 GiB,7.5,...,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,0,unavailable
504,P4D Highest Performance GPU 24xlarge,p4d.24xlarge,1152.0,345 units,96,12.00 GiB/vCPU,8,NVIDIA A100,320 GiB,8.0,...,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,unavailable,0,unavailable

### Selecting Required Columns

In [189]:
dataset = df[['API Name','Memory','vCPUs','Linux On Demand cost','Linux Reserved cost','Linux Spot Minimum cost','Linux Spot Maximum cost']]
dataset

,API Name,Memory,vCPUs,Linux On Demand cost,Linux Reserved cost,Linux Spot Minimum cost,Linux Spot Maximum cost
0,m6a.24xlarge,384.0,96,4.1472,2.74337,1.7303,2.253
1,m5dn.xlarge,16.0,4,0.272,0.171,0.0715,0.2078
2,c6a.8xlarge,64.0,32,1.224,0.80968,0.5441,0.5441
3,g5.16xlarge,256.0,64,4.096,2.58048,1.2288,1.3166
4,r5ad.16xlarge,512.0,64,4.192,2.641,1.14,1.7962
...,...,...,...,...,...,...,...
500,t3.large,8.0,2,0.0832,0.0522,0.0252,0.0312
501,vt1.6xlarge,48.0,24,1.3,0.819,0.39,0.39
502,u-9tb1.metal,9216.0,448,unavailable,unavailable,unavailable,unavailable
503,g4dn.12xlarge,192.0,48,3.912,2.465,1.2619,1.8177
504,p4d.24xlarge,1152.0,96,32.7726,20.175498,9.8318,10.1072

### Sorting Data based on Memory, vCPUs, Linux On Demand cost, Linux Reserved cost, Linux Spot Minimum cost and Linux Spot Maximum cost

In [190]:
Sorted_data = dataset.sort_values(by=['Memory', 'vCPUs', 'Linux On Demand cost', 'Linux Reserved cost', 'Linux Spot Minimum cost', 'Linux Spot Maximum cost']).reset_index(drop=True)
Sorted_data
# Sorted_data.to_csv('sorted_data.csv', index=False)

,API Name,Memory,vCPUs,Linux On Demand cost,Linux Reserved cost,Linux Spot Minimum cost,Linux Spot Maximum cost
0,t2.nano,0.500,1,0.0058,0.0036,unavailable,unavailable
1,t4g.nano,0.500,2,0.0042,0.0026,0.0016,0.0027
2,t3a.nano,0.500,2,0.0047,0.0029,0.0018,0.0021
3,t3.nano,0.500,2,0.0052,0.0033,0.0016,0.0016
4,t1.micro,0.613,1,0.02,0.014,0.002,0.002
...,...,...,...,...,...,...,...
500,u-9tb1.metal,9216.000,448,unavailable,unavailable,unavailable,unavailable
501,u-12tb1.112xlarge,12288.000,448,109.2,67.30542,unavailable,unavailable
502,u-12tb1.metal,12288.000,448,unavailable,unavailable,unavailable,unavailable
503,u-18tb1.metal,18432.000,448,unavailable,unavailable,unavailable,unavailable
504,u-24tb1.metal,24576.000,448,unavailable,unavailable,unavailable,unavailable

## ***Taking Input Data***

In [191]:
CPU = 10
Memory = 19
instance_type = 'i2.4xlarge'
price_Linux_On_Demand_Cost = Sorted_data.loc[Sorted_data['API Name'] == instance_type, 'Linux On Demand cost'].iloc[0]
price_Linux_Reserved_Cost = Sorted_data.loc[Sorted_data['API Name'] == instance_type, 'Linux Reserved cost'].iloc[0]
price_Linux_Spot_Minimum_Cost = Sorted_data.loc[Sorted_data['API Name'] == instance_type, 'Linux Spot Minimum cost'].iloc[0]
price_Linux_Spot_Maximum_Cost = Sorted_data.loc[Sorted_data['API Name'] == instance_type, 'Linux Spot Maximum cost'].iloc[0]
print(price_Linux_On_Demand_Cost)
print(price_Linux_Reserved_Cost)
print(price_Linux_Spot_Minimum_Cost)
print(price_Linux_Spot_Maximum_Cost)

3.41
1.696
1.023
1.0521

### Getting the index value by taking thresold as 80%

In [221]:
Index_Memory = Sorted_data.loc[(Sorted_data['Memory'] * 0.8 >= Memory) &(Sorted_data['vCPUs'] * 0.8 >= CPU)].index[0]
print(Sorted_data.loc[Index_Memory])

API Name                   c4.4xlarge
Memory                           30.0
vCPUs                              16
Linux On Demand cost            0.796
Linux Reserved cost             0.504
Linux Spot Minimum cost        0.2468
Linux Spot Maximum cost        0.3321
Name: 140, dtype: object

# ***Output***

In [218]:
count = 1 #Counter value to display the number of suggestions

for i in range(Index_Memory, Index_Memory-5,-1):
    print("\tSuggestion: ",count)
    print(Sorted_data.loc[i],'\n')
    
    # Prining the price saved for Linux On Demand Cost
    price_Linux_On_Demand_Cost_Index_Memory = Sorted_data.loc[i, 'Linux On Demand cost']
    Price_saved_Linux_On_Demand_Cost = round(float(price_Linux_On_Demand_Cost) - float(price_Linux_On_Demand_Cost_Index_Memory), 2)
    print('For Linux on Demand price will saved by $', round(Price_saved_Linux_On_Demand_Cost, 2), '\hour | $', round(Price_saved_Linux_On_Demand_Cost*24, 2), '\day | $', round(Price_saved_Linux_On_Demand_Cost*24*30, 2), '\month | $', round(Price_saved_Linux_On_Demand_Cost*24*365, 2), '\year')

    # Prining the price saved for Linux Reserved Cost
    price_Linux_Reserved_Cost_Index_Memory = Sorted_data.loc[i, 'Linux Reserved cost']
    Price_saved_Linux_Reserved_Cost = round(float(price_Linux_Reserved_Cost) - float(price_Linux_Reserved_Cost_Index_Memory), 2)
    print('For Linux Reserved price will saved by $', round(Price_saved_Linux_Reserved_Cost, 2), '\hour | $', round(Price_saved_Linux_Reserved_Cost*24, 2), '\day | $', round(Price_saved_Linux_Reserved_Cost*24*30, 2), '\month | $', round(Price_saved_Linux_Reserved_Cost*24*365, 2), '\year')

    # Prining the price saved for Linux Spot Minimum Cost
    price_Linux_Spot_Minimum_Cost_Index_Memory = Sorted_data.loc[i, 'Linux Spot Minimum cost']
    Price_saved_Linux_Spot_Minimum_Cost = round(float(price_Linux_Spot_Minimum_Cost) - float(price_Linux_Spot_Minimum_Cost_Index_Memory), 2)
    print('For Linux Spot Minimum Price will saved by $', round(Price_saved_Linux_Spot_Minimum_Cost, 2), '\hour | $', round(Price_saved_Linux_Spot_Minimum_Cost*24, 2), '\day | $', round(Price_saved_Linux_Spot_Minimum_Cost*24*30, 2), '\month | $', round(Price_saved_Linux_Spot_Minimum_Cost*24*365, 2), '\year')

    print('\n-----------------------------------------------------------------------------------------------------\n')
    count += 1

	Suggestion:  1
API Name                   c4.4xlarge
Memory                           30.0
vCPUs                              16
Linux On Demand cost            0.796
Linux Reserved cost             0.504
Linux Spot Minimum cost        0.2468
Linux Spot Maximum cost        0.3321
Name: 140, dtype: object

For Linux on Demand price will saved by $ 2.61 \hour | $ 62.64 \day | $ 1879.2 \month | $ 22863.6 \year
For Linux Reserved price will saved by $ 1.19 \hour | $ 28.56 \day | $ 856.8 \month | $ 10424.4 \year
For Linux Spot Minimum Price will saved by $ 0.78 \hour | $ 18.72 \day | $ 561.6 \month | $ 6832.8 \year

-----------------------------------------------------------------------------------------------------

	Suggestion:  2
API Name                   m3.2xlarge
Memory                           30.0
vCPUs                               8
Linux On Demand cost            0.532
Linux Reserved cost              0.38
Linux Spot Minimum cost        0.1494
Linux Spot Maximum cost        0.1925
Name: 139, dtype: object

For Linux on Demand price will saved by $ 2.88 \hour | $ 69.12 \day | $ 2073.6 \month | $ 25228.8 \year
For Linux Reserved price will saved by $ 1.32 \hour | $ 31.68 \day | $ 950.4 \month | $ 11563.2 \year
For Linux Spot Minimum Price will saved by $ 0.87 \hour | $ 20.88 \day | $ 626.4 \month | $ 7621.2 \year

-----------------------------------------------------------------------------------------------------

	Suggestion:  3
API Name                   vt1.3xlarge
Memory                            24.0
vCPUs                               12
Linux On Demand cost              0.65
Linux Reserved cost             0.4095
Linux Spot Minimum cost          0.195
Linux Spot Maximum cost          0.195
Name: 138, dtype: object

For Linux on Demand price will saved by $ 2.76 \hour | $ 66.24 \day | $ 1987.2 \month | $ 24177.6 \year
For Linux Reserved price will saved by $ 1.29 \hour | $ 30.96 \day | $ 928.8 \month | $ 11300.4 \year
For Linux Spot Minimum Price will saved by $ 0.83 \hour | $ 19.92 \day | $ 597.6 \month | $ 7270.8 \year

-----------------------------------------------------------------------------------------------------

	Suggestion:  4
API Name                   is4gen.xlarge
Memory                              24.0
vCPUs                                  4
Linux On Demand cost              0.5763
Linux Reserved cost              0.39306
Linux Spot Minimum cost           0.1729
Linux Spot Maximum cost           0.1729
Name: 137, dtype: object

For Linux on Demand price will saved by $ 2.83 \hour | $ 67.92 \day | $ 2037.6 \month | $ 24790.8 \year
For Linux Reserved price will saved by $ 1.3 \hour | $ 31.2 \day | $ 936.0 \month | $ 11388.0 \year
For Linux Spot Minimum Price will saved by $ 0.85 \hour | $ 20.4 \day | $ 612.0 \month | $ 7446.0 \year

-----------------------------------------------------------------------------------------------------

	Suggestion:  5
API Name                   c5n.2xlarge
Memory                            21.0
vCPUs                                8
Linux On Demand cost             0.432
Linux Reserved cost              0.272
Linux Spot Minimum cost         0.1295
Linux Spot Maximum cost         0.2457
Name: 136, dtype: object

For Linux on Demand price will saved by $ 2.98 \hour | $ 71.52 \day | $ 2145.6 \month | $ 26104.8 \year
For Linux Reserved price will saved by $ 1.42 \hour | $ 34.08 \day | $ 1022.4 \month | $ 12439.2 \year
For Linux Spot Minimum Price will saved by $ 0.89 \hour | $ 21.36 \day | $ 640.8 \month | $ 7796.4 \year

-----------------------------------------------------------------------------------------------------