In [2]:
import matplotlib as plt
import pandas as pd

In [5]:
df = pd.read_csv('aws_instance_types_with_pricing.csv')
df

,Type,VCPU,Memory (GiB),Storage (GB),Network Performance,EBS-Optimized,Price (USD)
0,c6a.24xlarge,96,192.0,0,37.5 Gigabit,30000.0,NaN
1,c7a.medium,1,2.0,0,Up to 12.5 Gigabit,325.0,NaN
2,r6in.metal,128,1024.0,0,200 Gigabit,100000.0,NaN
3,r7iz.16xlarge,64,512.0,0,25 Gigabit,20000.0,NaN
4,r7iz.8xlarge,32,256.0,0,12.5 Gigabit,10000.0,NaN
...,...,...,...,...,...,...,...
95,r7a.2xlarge,8,64.0,0,Up to 12.5 Gigabit,2500.0,NaN
96,m7i.metal-24xl,96,384.0,0,37.5 Gigabit,30000.0,NaN
97,m6gd.12xlarge,48,192.0,0,20 Gigabit,14250.0,NaN
98,r6a.2xlarge,8,64.0,0,Up to 12.5 Gigabit,2500.0,NaN
99,i4i.16xlarge,64,512.0,0,37.5 Gigabit,20000.0,NaN

In [9]:
selected = df[['Type','VCPU','Memory (GiB)']]
selected

              Type  VCPU  Memory (GiB)
0     c6a.24xlarge    96         192.0
1       c7a.medium     1           2.0
2       r6in.metal   128        1024.0
3    r7iz.16xlarge    64         512.0
4     r7iz.8xlarge    32         256.0
..             ...   ...           ...
95     r7a.2xlarge     8          64.0
96  m7i.metal-24xl    96         384.0
97   m6gd.12xlarge    48         192.0
98     r6a.2xlarge     8          64.0
99    i4i.16xlarge    64         512.0

[100 rows x 3 columns]

In [12]:
sort_df = selected.sort_values(by=['VCPU','Memory'])
sort_df

             Type  VCPU  Memory (GiB)
85       t1.micro     1      0.612305
1      c7a.medium     1      2.000000
49    c7gd.medium     1      2.000000
12     r6g.medium     1      8.000000
61    r6gd.medium     1      8.000000
..            ...   ...           ...
2      r6in.metal   128   1024.000000
32   r7a.32xlarge   128   1024.000000
76   c6a.48xlarge   192    384.000000
24  inf2.48xlarge   192    768.000000
57      r6a.metal   192   1536.000000

[100 rows x 3 columns]

In [13]:
# User data

In [15]:
user_df = pd.read_csv('ec2_instances_data.csv')
user_df

,instance_id,instance_type,ram_utilization_avg,cpu_utilization_avg,highest_ram_utilization,highest_cpu_utilization,price
0,i-031e1119dd7330e66,t2.micro,74.1,16.1,73.9,17.5,NaN

In [25]:
user_selected = user_df.drop(columns=['price','highest_ram_utilization','highest_cpu_utilization'])
user_selected

           instance_id instance_type  ram_utilization_avg  cpu_utilization_avg
0  i-031e1119dd7330e66      t2.micro                 74.1                 16.1